### PR TITLE
Put our socket and pidfile in our private directory

### PR DESCRIPTION
**Pull request by pprindeville**
Can't run as non-privileged user and create files/sockets in /usr/var or wherever...

### CODE REVIEW

**Comment by pprindeville** [comment]
@olofhagsand Trivial change.

**Comment by olofhagsand** [comment]
The CI fails both for native and for docker jobs. please investigate

**Comment by olofhagsand** [comment]
Fixed CI, due to unlimited openconfig autocli causing mem overflow.
Please rebase.

**Comment by pprindeville** [comment]
Rebased.

**Pull request merged**
